### ISSUE TITLE
first pixel is wrong with ringWidth=1 (possible rounding issue)

### ISSUE THREAD

**Issue by neoneye** [maxkonovalov/MKRingProgressView#20]
![Image of 1px circle glitch](https://i.imgur.com/G9OGV2E.png)

I changed from `CGPoint(x: x, y: y)` to `CGPoint(x: x + 1, y: y)` in the `MKGradientGenerator.gradientImage()` function:
```
// after
let c = pixelDataForGradient(type, colors: [colors, colors2], locations: [locations, locations2], startPoints: [startPoint, startPoint2], endPoints: [endPoint, endPoint2], point: CGPoint(x: x + 1, y: y), size: CGSize(width: w, height: h))

// before
let c = pixelDataForGradient(type, colors: [colors, colors2], locations: [locations, locations2], startPoints: [startPoint, startPoint2], endPoints: [endPoint, endPoint2], point: CGPoint(x: x, y: y), size: CGSize(width: w, height: h))
```

My setup:
```
ring.startColor = UIColor(hex6: 0xFF0000)
ring.endColor = UIColor(hex6: 0x00FF00)
ring.backgroundRingColor = UIColor(hex6: 0x000000)
ring.ringWidth = 1
ring.shadowOpacity = 0
ring.progress = 0.75
ring.style = .square
```

I use:
- Xcode 8.3.2
- MKRingProgressView commit `c2db5129293d0ff990c0e7052ee0f708d8dcc8d7`

**Comment by maxkonovalov** [comment]
@neoneye this actually happens because of the quality of generated gradient image being reduced by default for better performance. 
You can try setting `ring.gradientImageScale = UIScreen.main.scale` - it will generate high res backdrop gradient that should precisely match a small-width ring. This shouldn't have any performance problems for small rings anyway.
Let me know if it helps!

**Comment by neoneye** [comment]
It works. I just tried it. Thank you @maxkonovalov

**Comment by maxkonovalov** [comment]
@neoneye you are welcome!
