### ISSUE TITLE
Ring gradient starting from some progress?

### ISSUE THREAD

**Issue by khetaram** [maxkonovalov/MKRingProgressView#26]
Hi,

I want ring gradient color to start from some % of progress.

For example if ring start color is red, end color is white and ring progress is 1.5 then,

 I need ring till progress 0.8 color to be red and then start gradient for rest of string.

How can i achieve it?

Thanks in advance

**Comment by maxkonovalov** [comment]
Hi @khetaram,
The only suggestion I can make is subclassing the control or modifying the source directly. What you need is override `func gradientImage() -> CGImage`, so that it uses the locations and colors you want.  Also some changes to `func contentImage() -> CGImage?` might be required to match your custom gradient defined in the first function.

**Comment by khetaram** [comment]
Hi Max,

Can you send overridden method to me so i can compare both and change
accordingly. As i am not able to understand it properly.  It would be great
if you can help me out.
